-- Spacebar as the leader key
vim.g.mapleader = " "

-- Key mappings
vim.keymap.set('n', ';', ':', { noremap = true })
vim.keymap.set('n', '<ESC><ESC>', ':nohl<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>q', ':q<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '{', ':bprev<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '}', ':bnext<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>[', ':bprev<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>]', ':bnext<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>w', ':bdelete<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<leader>W', ':bdelete!<CR>', { noremap = true, silent = true })
vim.keymap.set('i', '<C-a>', '<Home>', { noremap = true, silent = true })
vim.keymap.set('i', '<C-e>', '<End>', { noremap = true, silent = true })
vim.keymap.set('i', '<C-n>', '<Down>', { noremap = true, silent = true })
vim.keymap.set('i', '<C-p>', '<Up>', { noremap = true, silent = true })
vim.keymap.set('i', '<C-b>', '<Left>', { noremap = true, silent = true })
vim.keymap.set('i', '<C-f>', '<Right>', { noremap = true, silent = true })
vim.keymap.set('i', '<C-h>', '<BS>', { noremap = true, silent = true })
vim.keymap.set('i', '<C-d>', '<Del>', { noremap = true, silent = true })
vim.keymap.set('n', '<C-w>-', ':sp<CR>', { noremap = true })
vim.keymap.set('n', '<C-w>\\', ':vs<CR>', { noremap = true })
vim.keymap.set('n', '<M->', ':sp<CR>', { noremap = true })
vim.keymap.set('n', '<M-\\>', ':vs<CR>', { noremap = true })
vim.keymap.set('n', '<C-h>', '<C-w>h', { noremap = true })
vim.keymap.set('n', '<C-j>', '<C-w>j', { noremap = true })
vim.keymap.set('n', '<C-k>', '<C-w>k', { noremap = true })
vim.keymap.set('n', '<C-l>', '<C-w>l', { noremap = true })
vim.keymap.set('n', '<M-j>', '<C-w>-', { noremap = true })
vim.keymap.set('n', '<M-k>', '<C-w>+', { noremap = true })
vim.keymap.set('n', '<M-l>', '<C-w>>', { noremap = true })
vim.keymap.set('n', '<M-h>', '<C-w><', { noremap = true })
vim.keymap.set('n', '<M-r>', '<C-w>=', { noremap = true })
vim.keymap.set('n', '<M-a>', '<C-w>_<C-w>|', { noremap = true })
vim.keymap.set('t', '\\', '<C-\\><C-n>', { noremap = true, silent = true })
