abbr --add --global ph "phantom"
abbr --add --global phc "phantom create"
abbr --add --global pha "phantom attach"
abbr --add --global phl "phantom list"
abbr --add --global phw "phantom where"
abbr --add --global phd "phantom delete"
abbr --add --global phe "phantom exec"
abbr --add --global phr "phantom review"
abbr --add --global phs "phantom shell"
abbr --add --global phv "phantom version"
abbr --add --global phm "phantom mcp"
abbr --add --global phg "phantom github"
abbr --add --global phgco "phantom github checkout"

