#!/bin/sh

if test "$(/usr/bin/uname)" != "Darwin"; then
  brew $@
elif test "$(/usr/bin/uname -m)" = "arm64"; then
  echo 'Apple Silicon'
  /opt/homebrew/bin/brew $@
else
  echo 'Intel'
  /usr/local/bin/brew $@
fi
