#!/bin/bash

find /Applications -type d -name "*.app" -maxdepth 2 | while read app; do
  name=$(basename "$app" ".app")
  path="$app/Contents/MacOS/$name"

  test ! -f "$path" && continue

  lipo -archs "$path" | grep arm64 > /dev/null
  test $? == 0 && continue

  echo $app
done
