#!/bin/sh

args=$@

function launch() {
  path=$1
  test ! -d "$path" && return

  open -na "$path" --args "$args"
  exit 0
}

launch "/Applications/IntelliJ IDEA.app"
launch "$HOME/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app"
launch "/Applications/IntelliJ IDEA CE.app"
launch "$HOME/Applications/JetBrains Toolbox/IntelliJ IDEA Community Edition.app"

echo '"IntelliJ IDEA" is not found.'
exit 1
